language: python
python:
    - 3.7
install: pip install -U tox-travis
script: tox
deploy:
    provider: pypi
    server: https://upload.pypi.org/legacy/
    distributions: sdist bdist_wheel
    user: __token__
    password: $PYPI_TOKEN
    skip_cleanup: false
    on:
        tags: true
        repo: kingsdigitallab/DataPortalExplorer
        python: 3.7
