language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jmiguelv
  password:
    secure: DjI4JMOl5aBoy0h9WsKVOYTQviNAoUPLvRPvtZJHQHlom03/8rXzVXyJ1hEDcTPl6M4A6TM/DDW5rlsetw3EG4PX5MHbXlTk/trt0eXQxYxwUHtn9Hbs2EFsQItDN4ZQTBk7etXfhq04IPNsoT7MSl6FpLs0OJbYbLVvrb1ID295CzbKE+lxIMdpvBJmXD356O2Mv9SWaPpFhx8qS5mjSN+U9AwOU6bwn0/Kvm0FjngxUiSo0wwfU7XesWlPHiezsXf4YH+VtTUGCtXcr17nwY0rsR4xpcrcaYCG+VG308jNGWA3tvX5rxofWiTKtY48Ybg327LNuoNFsZw+gDdpLKnv6Y806wdanm+Du5WMpxM51KbIPX6alcDqv5WRowv+R6uBeXIARkbMEOoNQk3qP2fybLJSNMXLS0GnduOSrTURrHWzfpTgR4XV3yQChGiw3B86q4qX2zBHY3uhIqlG6KHeVCCJO0OZarqXwP1ee0jWYswTtKMWp1RE0+TKj1gkFPAFg1i1xxDm1K9sKx5oVHgNewjsqq80BKTNPOFTPrL/Xy7pz93ODJGTIwsIoA9VNj1TNuJt2kfaH8kata4/jFpYBxkCUKGHjAF1QR6pxuFbb9YcVIO4pQZxJy3kPz+wCGPHA6i94mPBN0QSRBjlafmHtW0wZEWcjU0iF6cZBbI=
  on:
    tags: true
    repo: kingsdigitallab/DataPortalExplorer
    python: 3.7
