language: python
python:
    - 3.7
install: pip install -U tox-travis
script: tox
deploy:
    provider: pypi
    server: https://upload.pypi.org/legacy/
    distributions: sdist bdist_wheel
    user: jmiguelv
    password:
        secure: iKYPK18T6uXMKwE+F5j3Km6MU5N06RVtZuBs53n5Viat3BZkkuij4V6Q/ucQG/24HfLxR2v6E94mmxIXFxpLZblamHV829UCJPrW0creBUSvLeV6ZDnieOkZxK/x2+nT30aQbx83SOY2P9U1gvG+l09jMoVul7s0khS3xgqwJ3ssbRMHj1PxZHbL5jk0Nq7YvAcmX0R+ilEZXRYVCkh5CWLysBQSAY0+xhAaHvkjB1nUroK6OTIjQ3JJkx8HLmUDWjSqoIMStVZ/pUkvbeJvvsxYJ7e19LYrZowyl3m3zvwCecPt5Bga9ItAvUVo7OjjwAbI7L1jtvXcrAFFHpjvYshQ78kTVpH8mxdcLAPMmXDNmHSgL8YjnJWraf9QwVcmmFYpTWaufeSWtKulDP6AcVKQx2ILI3nLNdGsok8ohu16UC1qywKBP6sA9EoTiy65phgGTpwAtWRvYchLqJQm4gFM4+wbJF7spuyxLLwITonAOSXbm2ThJnU87Nh+VbEYPQ+oHQ0zYNEoWswexqb2yrNcUtbTVXMhUdB5HL2ojw093XLPCId0afxkYfy6tZspA+q22tdfVQp5X+dKHKxjb3n0id9rU3OwZJtq9NYZ4HyoSd24uMQ1TfjStuo9nV7nauu9lX8yRG0RjkLwkqrwkb9MGWHTQvegvpgfXq9Pnm8=
    skip_cleanup: false
    on:
        tags: true
        repo: kingsdigitallab/DataPortalExplorer
        python: 3.7
