language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jmiguelv
  password:
    secure: pN2C07XfK9kP98ZNjavi31LoRhRE5IDDoUaBwTfqukr4I4ZQVPewaPDzfhbksGczm9uo+wl5L0CpdxrKk6HSMjcPYvqikXWiFkMmNQz7IdnDN9mU6tSFh0I1Ks128FZa4aufNhwXDZk7z/xA4WqunCfz5mAQKR2KPCB3N8Rx2BS7a56SEh93ZCrKUs3ENhsz0nOWDFfSqa8O+d3OQklbNHVDmZpCfzIsVY06ccRTCoMzWl6tc/Pb+vFJ1lvhjeRmXeo360/hiivMlOMcEHMZ7aHtZOnJApwG+au0vDGw/0yhOBYUGnbG5XzW/dQsEK1Kse9Zs5OWlkXTLj77Grr0KRhroEKBZC2iUn1ZR2G2TlbARaE3dDJFGiSYzQg79nAevtuV1qdKG8wHgROCWpXluHO3uEITRiLc5LWE9uMtedmdg1axgiNHHsoZn3Zd5Qya1S/EzRUArwliXbLbRArd6nz/+IaIqpObPnZ4Sq14IGXSF4xD0SKfy7fw0Y3Ccum6u9WXnI+hfHy9YABdD98jktw5tIkfWf/wTMakwzUvOiCLFZr9U7g4LBm3bfrJj/QZpmCk9ixuAwD9vEPb5/KoQN8i3+bC3u2ipv9ggnPLfpNTZtPcAkEF6f1kLHhLE1aCgbzuclnM0fVYYvsxR50SbsJ7L9D6INPd1f8ng3g/fsY=
  on:
    tags: true
    repo: kingsdigitallab/DataPortalExplorer
    python: 3.7
