language: python
python:
    - 3.7
install: pip install -U tox-travis
script: tox
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: jmiguelv
    password:
        secure: RPfYqwjvX9oBF9JMTJR7A2DwK+D+S7qDTyn8dHcrtpZqEu24sk2z4/MYoPp0h/orRzCffXhMpDTswmTmAkQRbm1S2wqQX0G6GDZItZwoqOXqtD8q0v1Kc9EIP4AIc+pc1KFbrAUWy7IqxiHLJZxZT2hRxIyU23CSlMxGXea35ECAwZD59xSvvzIBTta0DPUUC5pyXaUulM9jiY2rwDh6iBe0SFmpuC1upaLz7HE2cGcDyr7mecE66CuGGlRaeCAtXK0wubhFmJSQpYaUFIcTeEvaPpQTyVlpSoka3BAuYiNeVl8Lz65ZBvHT8FxoN+Q+lM0y48/p0AddEZK9r6qDZP81ZFjw7ALnAC9C9tz88/rIqP1rEaUWVA2mmENBjO3jP3DLXkjoEBiX3/bzMr97uAWXAAWWQRSRqtnHdwVh3AjPlR4qqwTtbYplksERQAGtETiOf3DJPvvjm3MugMNvQoXT7TkIpe6JX5wiFrDMsffZybjXvKPOO6IYyoP+wmgDonlVVNrHtYAqUiKM0p7qOBZq+DUtDierAnhHYcLWl2wX7wDEaGv+s9e1nbAgmxvrnsxyWH+RQR8tCsnrxUXBZN+69aOTncoQAk5IuO2U1CB2ufdXuYBb2cCBZcgrQVIVtvCK20Sn4VElQF8vC1vOMAcr6ShyatSI0E8hlqrkNNI=
    on:
        tags: true
        repo: kingsdigitallab/DataPortalExplorer
        python: 3.7
