# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
    push:
    pull_request:

jobs:
    test_build_deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt

            - name: tox
              run: |
                  tox

            - name: Build
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
              run: |
                  python setup.py clean sdist bdist_wheel

            - name: Publish a Python distribution to PyPI
              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_TOKEN }}
