# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements_dev.txt

            - name: tox
              run: |
                  tox

            - name: Build and deploy
            - uses: casperdcl/deploy-pypi@v2
                with:
                    password: ${{ secrets.PYPI_TOKEN }}
                    build: true
                    # only upload if a tag is pushed (otherwise just build & check)
                    upload: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
